### ISSUE TITLE
runtime.LockOSThread() not working with Google App Engine (GAE)

### ISSUE THREAD

**Issue by fnkr** [twinj/uuid#11]
I cannot deploy to Google App Engine because your package uses `runtime.LockOSThread()`.
I made a fork and removed every usage of the `runtime` package but `NewV1()` is probably broken now. Is there some other way to get rid of it?

```diff
diff --git a/rfc4122.go b/rfc4122.go
index f53826b..b7931ff 100644
--- a/rfc4122.go
+++ b/rfc4122.go
@@ -13,7 +13,6 @@ import (
 	"encoding/binary"
 	"log"
 	"net"
-	"runtime"
 	seed "math/rand"
 )
 
@@ -52,11 +51,11 @@ func init() {
 
 // NewV1 will generate a new RFC4122 version 1 UUID
 func NewV1() UUID {
-	runtime.LockOSThread()
 	now := currentUUIDTimestamp()
 	state.read(now, currentUUIDNodeId())
 	state.persist()
-	runtime.UnlockOSThread()
 	return formatV1(now, 1, ReservedRFC4122, state.node)
 }
 ```

**Comment by twinj** [comment]
This is the standard way of generating a V1 uuid. I'll have to look into variants. I started looking at creating interfaces to handle this case once. I believe the lock is there to stop a race condition. Can't remember at the moment so bear with me. There has to be a better way?

**Comment by twinj** [comment]
In the state file set this to false as well

const (
	// If true uuid V1 will save state in a temp dir
	V1Save = false
)

The thread lock is there to stop a race condition. It is not thread safe without it. I am considering ripping out v1 to its own library as it just add complexity that is not required by most people. (I may be wrong)

In GAP if you remove runtime package and have the above as false it will not cause an issue for you.

In the meantime I will consider several solutions to this problem.

**Comment by twinj** [comment]
I have removed the runtime package and replaced with sync.
