### ISSUE TITLE
Parsed UUID's do not match the original as a key

### ISSUE THREAD

**Issue by Alex-Addy** [twinj/uuid#19]
While using this library I noticed some strange behaviour. Namely that the following test will fail:

```go
func TestUUIDHashEquality(t *testing.T) {
	id := uuid.NewV4()
	sId := id.String()
	pId, err := uuid.FromString(sId)

	assert.Nil(t, err)
	assert.Equal(t, id, pId)

	m := make(map[uuid.UUID]string)
	m[id] = "Testify"
	assert.Equal(t, "Testify", m[pId])
}
```

This was very unexpected and if you can't fix it, it should at least be noted somewhere.

**Comment by twinj** [comment]
I'll have a look into it. Sry for delay.

**Comment by twinj** [comment]
The assert.Equal uses reflection and deep equal to test equality, it de-references pointers and gets to the elements of the objects passed in, this is what is misleading. Two different instances of an UUID from the same string are not equal if they do not live in the same memory location. A UUID bytes can be compared by deep equal only if they use the same underlying type. If you were to base it off a NewV1 this would fail.

`      map[uuid.UUID]string`

When you put a UUID  in the map you are essentially putting in a reference not the bytes. Then when you attempt to retrieve another reference from the map, via pId in this instance it correctly returns an empty string as that reference has not yet been added to the map.

I simplified the standing problem with this code to demonstrate how UUIDs compare. 

`

	func TestHashEqualityString(t *testing.T) {
		temp := "1"
		temp2 := temp
	
		id := &temp
		pId := &temp2
	
		assert.True(t, *id == *pId)
		assert.True(t, id == pId)
	}


	func TestHashEqualityString(t *testing.T) {
		temp := "1"
		temp2 := temp

		id := &temp
		pId := &temp2
		
		m := make(map[*string]string)
		m[id] = "Testify"
		assert.Equal(t, "Testify", m[pId])
	}

`

To test equalness use the uuid.Equal method. For now I will investigate options.
