### ISSUE TITLE
state.init failed on Windows

### ISSUE THREAD

**Issue by easeway** [twinj/uuid#9]
rfc4122.go line 133
if (inter.Flags&(1<<net.FlagUp)) != 0 

Is not satisfied on Windows, and causes state.init failure. If comment out this if statement, it works.

I found the problem on Windows Server 2012 R2, not tested on other Windows editions.

**Comment by Htbaa** [comment]
This (seems) to have happened to me as well on Windows Server 2012 R2. My usage of the library is as followed:

``id := uuid.Formatter(uuid.NewV4(), uuid.CleanHyphen)``

**Comment by twinj** [comment]
Ok. Is there any log output? I cannot recreate this issue in a standard environment. 

State init failure should not be fatal.

**Comment by Htbaa** [comment]
My console outputs this: `2015/06/22 10:03:43 UUID.State.init: address error: <nil>`

It's indeed not fatal and my application is generating UUID's just fine.

**Comment by twinj** [comment]
By default now you should not see this error unless you attempt to start saving state for use in V1 uuids. The default is now to randomly generate the node rather than find the node through the hardware. Thanks for reporting the issue.

**Comment by Htbaa** [comment]
Thanks.
